CREATE TABLE `assetAttributes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assetId` int NOT NULL,
	`componentId` int,
	`organizationId` int,
	`attributeKey` varchar(100) NOT NULL,
	`attributeCategory` enum('identity','technical','operational','financial','compliance') NOT NULL,
	`valueText` text,
	`valueNumeric` decimal(20,6),
	`valueBoolean` boolean,
	`valueDate` date,
	`valueJson` json,
	`unit` varchar(20),
	`version` int DEFAULT 1,
	`previousVersionId` int,
	`isCurrent` boolean DEFAULT true,
	`sourceType` enum('document','api','manual','ai_extraction','iot','work_order') NOT NULL,
	`sourceId` int,
	`sourcePage` int,
	`sourceSnippet` text,
	`sourceConfidence` decimal(3,2),
	`verificationStatus` enum('unverified','verified','rejected') DEFAULT 'unverified',
	`verifiedById` int,
	`verifiedAt` timestamp,
	`rejectionReason` text,
	`contentHash` varchar(64) NOT NULL,
	`timestampAnchor` timestamp DEFAULT (now()),
	`aiAssessed` boolean DEFAULT false,
	`aiAssessmentResult` json,
	`aiRoutedFrom` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdById` int,
	`supersededAt` timestamp,
	`supersededById` int,
	CONSTRAINT `assetAttributes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assetComponents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assetId` int NOT NULL,
	`organizationId` int,
	`name` varchar(255) NOT NULL,
	`componentType` enum('fan','capacitor','fuse','connector','display','sensor','relay','other') NOT NULL,
	`manufacturer` varchar(255),
	`model` varchar(255),
	`serialNumber` varchar(255),
	`status` enum('active','inactive','failed','replaced') DEFAULT 'active',
	`installationDate` date,
	`replacementDate` date,
	`specifications` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assetComponents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`systemId` int NOT NULL,
	`siteId` int NOT NULL,
	`projectId` int,
	`organizationId` int,
	`vatrId` varchar(100),
	`assetType` enum('inverter','panel','meter','battery','transformer','combiner_box','tracker','monitoring','genset','switchgear','cable','other') NOT NULL,
	`assetCategory` enum('generation','storage','distribution','monitoring','auxiliary') NOT NULL,
	`name` varchar(255) NOT NULL,
	`manufacturer` varchar(255),
	`model` varchar(255),
	`serialNumber` varchar(255),
	`assetTag` varchar(100),
	`nominalCapacityKw` decimal(12,2),
	`nominalCapacityKwh` decimal(12,2),
	`voltageRating` decimal(10,2),
	`currentRating` decimal(10,2),
	`efficiencyRating` decimal(5,2),
	`locationOnSite` varchar(255),
	`gpsLatitude` decimal(10,6),
	`gpsLongitude` decimal(10,6),
	`installationDate` date,
	`status` enum('active','inactive','failed','replaced','decommissioned') DEFAULT 'active',
	`condition` enum('excellent','good','fair','poor','failed') DEFAULT 'good',
	`lastInspectionDate` date,
	`nextMaintenanceDate` date,
	`warrantyStartDate` date,
	`warrantyEndDate` date,
	`warrantyProvider` varchar(255),
	`warrantyDocumentId` int,
	`purchasePrice` decimal(12,2),
	`purchaseCurrency` varchar(3) DEFAULT 'USD',
	`purchaseDate` date,
	`supplier` varchar(255),
	`depreciationMethod` varchar(50),
	`usefulLifeYears` int,
	`currentVersion` int DEFAULT 1,
	`contentHash` varchar(64),
	`previousVersionId` int,
	`profileCompletenessPct` decimal(5,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdById` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedById` int,
	CONSTRAINT `assets_id` PRIMARY KEY(`id`),
	CONSTRAINT `assets_vatrId_unique` UNIQUE(`vatrId`)
);
--> statement-breakpoint
CREATE TABLE `attributeChangeLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attributeId` int NOT NULL,
	`assetId` int NOT NULL,
	`changeType` enum('created','updated','deleted','verified','rejected') NOT NULL,
	`oldValueHash` varchar(64),
	`newValueHash` varchar(64),
	`oldSnapshot` json,
	`newSnapshot` json,
	`changedById` int,
	`changedAt` timestamp NOT NULL DEFAULT (now()),
	`changeReason` text,
	CONSTRAINT `attributeChangeLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenanceSchedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`scopeType` enum('site','system','asset') NOT NULL,
	`scopeId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`maintenanceType` enum('preventive','predictive','condition_based') NOT NULL,
	`taskCategory` enum('inspection','cleaning','calibration','replacement','testing','repair'),
	`frequencyType` enum('calendar','runtime','cycles','condition') NOT NULL,
	`frequencyValue` int,
	`frequencyUnit` enum('days','weeks','months','years','hours','cycles'),
	`triggerMetric` varchar(100),
	`triggerThreshold` decimal(12,2),
	`triggerOperator` enum('gt','lt','eq'),
	`estimatedDurationHours` decimal(6,2),
	`requiredSkills` json,
	`requiredParts` json,
	`safetyRequirements` json,
	`procedureDocumentId` int,
	`defaultAssigneeId` int,
	`defaultTeam` varchar(100),
	`status` enum('active','paused','archived') DEFAULT 'active',
	`lastGeneratedAt` timestamp,
	`nextDueDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdById` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenanceSchedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partsUsage` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partId` int NOT NULL,
	`workOrderId` int,
	`assetId` int,
	`quantity` int NOT NULL,
	`usageType` enum('consumed','returned','damaged') DEFAULT 'consumed',
	`usedById` int,
	`usedAt` timestamp NOT NULL DEFAULT (now()),
	`notes` text,
	CONSTRAINT `partsUsage_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sites` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`portfolioId` int,
	`organizationId` int,
	`name` varchar(255) NOT NULL,
	`siteCode` varchar(50),
	`description` text,
	`address` text,
	`city` varchar(100),
	`stateProvince` varchar(100),
	`country` varchar(100) NOT NULL DEFAULT 'Nigeria',
	`latitude` decimal(10,6),
	`longitude` decimal(10,6),
	`timezone` varchar(50) DEFAULT 'Africa/Lagos',
	`siteType` enum('ground_mount','rooftop','carport','floating','minigrid') DEFAULT 'ground_mount',
	`landType` enum('owned','leased','easement') DEFAULT 'leased',
	`gridConnection` enum('grid_tied','off_grid','hybrid') DEFAULT 'grid_tied',
	`capacityKw` decimal(12,2),
	`capacityKwh` decimal(12,2),
	`status` enum('active','inactive','decommissioned') DEFAULT 'active',
	`operationalStatus` enum('online','offline','maintenance','commissioning') DEFAULT 'commissioning',
	`codDate` date,
	`profileCompletenessPct` decimal(5,2) DEFAULT '0',
	`lastProfileUpdate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sites_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `spareParts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`partNumber` varchar(100) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` enum('electrical','mechanical','consumable','safety','other'),
	`compatibleAssetTypes` json,
	`compatibleManufacturers` json,
	`compatibleModels` json,
	`quantityOnHand` int DEFAULT 0,
	`minimumStock` int DEFAULT 0,
	`reorderPoint` int DEFAULT 0,
	`reorderQuantity` int,
	`storageLocation` varchar(255),
	`siteId` int,
	`unitCost` decimal(12,2),
	`currency` varchar(3) DEFAULT 'USD',
	`preferredSupplier` varchar(255),
	`leadTimeDays` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `spareParts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `systems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`siteId` int NOT NULL,
	`organizationId` int,
	`name` varchar(255) NOT NULL,
	`systemType` enum('pv','bess','genset','hybrid','wind','hydro') NOT NULL,
	`topology` enum('dc_coupled','ac_coupled','standalone') DEFAULT 'standalone',
	`capacityKw` decimal(12,2),
	`capacityKwh` decimal(12,2),
	`configuration` json,
	`status` enum('active','inactive','maintenance') DEFAULT 'active',
	`commissionedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `systems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workOrderTasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workOrderId` int NOT NULL,
	`taskNumber` int NOT NULL,
	`description` text NOT NULL,
	`assetId` int,
	`componentId` int,
	`status` enum('pending','in_progress','completed','skipped') DEFAULT 'pending',
	`completedAt` timestamp,
	`completedById` int,
	`result` enum('pass','fail','na'),
	`resultNotes` text,
	`measurements` json,
	`attributeUpdates` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workOrderTasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `workOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`workOrderNumber` varchar(50) NOT NULL,
	`sourceType` enum('scheduled','reactive','inspection','alert') NOT NULL,
	`scheduleId` int,
	`alertId` int,
	`siteId` int NOT NULL,
	`systemId` int,
	`assetId` int,
	`title` varchar(500) NOT NULL,
	`description` text,
	`workType` enum('preventive','corrective','emergency','inspection') NOT NULL,
	`priority` enum('critical','high','medium','low') NOT NULL,
	`assignedToId` int,
	`assignedTeam` varchar(100),
	`scheduledStart` timestamp,
	`scheduledEnd` timestamp,
	`actualStart` timestamp,
	`actualEnd` timestamp,
	`estimatedHours` decimal(6,2),
	`actualHours` decimal(6,2),
	`status` enum('open','assigned','in_progress','on_hold','completed','cancelled') DEFAULT 'open',
	`statusReason` text,
	`completionNotes` text,
	`completionChecklist` json,
	`followUpRequired` boolean DEFAULT false,
	`followUpWorkOrderId` int,
	`laborCost` decimal(12,2),
	`partsCost` decimal(12,2),
	`otherCost` decimal(12,2),
	`assetAttributesUpdated` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdById` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workOrders_id` PRIMARY KEY(`id`),
	CONSTRAINT `workOrders_workOrderNumber_unique` UNIQUE(`workOrderNumber`)
);
