CREATE TABLE `artifactAudio` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`durationSeconds` int,
	`sampleRate` int,
	`channels` int,
	`bitrate` int,
	`recordedAt` timestamp,
	`recordingType` enum('voice_note','call','meeting','site_ambient'),
	`participants` json,
	`audioPreprocessingStatus` enum('pending','noise_reduction','diarization','complete') DEFAULT 'pending',
	`cleanedAudioUrl` text,
	`noiseReductionApplied` boolean DEFAULT false,
	`diarizationApplied` boolean DEFAULT false,
	`speakerCount` int,
	`transcriptStatus` enum('pending','processing','complete','failed') DEFAULT 'pending',
	`transcriptText` text,
	`transcriptSegments` json,
	`transcriptLanguage` varchar(10),
	`transcriptConfidence` decimal(5,4),
	`aiExtractionComplete` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactAudio_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactContracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`contractType` enum('ppa','lease','epc','om','financing','offtake','interconnection','insurance','other') NOT NULL,
	`contractNumber` varchar(100),
	`contractTitle` varchar(500),
	`parties` json,
	`counterpartyName` varchar(255),
	`counterpartyType` varchar(100),
	`effectiveDate` date,
	`expiryDate` date,
	`termYears` int,
	`renewalTerms` text,
	`contractValue` decimal(18,2),
	`currency` varchar(3),
	`paymentTerms` text,
	`ppaCapacityKw` decimal(12,2),
	`ppaTariffRate` decimal(10,4),
	`ppaTariffEscalation` decimal(5,2),
	`leaseAreaSqm` decimal(12,2),
	`leaseAnnualRent` decimal(18,2),
	`leaseEscalationPct` decimal(5,2),
	`contractStatus` enum('draft','negotiating','executed','active','expired','terminated') DEFAULT 'draft',
	`executionDate` date,
	`executedBy` varchar(255),
	`amendmentCount` int DEFAULT 0,
	`latestAmendmentDate` date,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactContracts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactEntityMentions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`extractionRunId` varchar(36),
	`mentionText` varchar(500) NOT NULL,
	`mentionType` enum('site','asset','company','person','location','date','amount','other') NOT NULL,
	`sourcePage` int,
	`sourceTimestampStart` decimal(10,2),
	`sourceTimestampEnd` decimal(10,2),
	`sourceSnippet` text,
	`resolvedEntityType` varchar(50),
	`resolvedEntityId` int,
	`resolutionConfidence` decimal(5,4),
	`resolutionStatus` enum('unresolved','auto_resolved','manual_resolved','ignored') DEFAULT 'unresolved',
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactEntityMentions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactExtractions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`artifactVersion` int,
	`extractionRunId` varchar(36) NOT NULL,
	`extractionModel` varchar(50),
	`extractionPromptVersion` varchar(20),
	`extractedAt` timestamp NOT NULL DEFAULT (now()),
	`fieldKey` varchar(100) NOT NULL,
	`fieldCategory` enum('identity','technical','commercial','legal','financial','operational','compliance') NOT NULL,
	`extractedValueText` text,
	`extractedValueNumeric` decimal(18,4),
	`extractedValueDate` date,
	`extractedValueBoolean` boolean,
	`extractedValueJson` json,
	`unit` varchar(50),
	`sourceType` enum('page','timestamp','segment','cell'),
	`sourcePage` int,
	`sourceTimestampStart` decimal(10,2),
	`sourceTimestampEnd` decimal(10,2),
	`sourceCellReference` varchar(20),
	`sourceSnippet` text,
	`confidence` decimal(5,4) NOT NULL,
	`extractionNotes` text,
	`verificationStatus` enum('unverified','verified','rejected','corrected') DEFAULT 'unverified',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`verificationNotes` text,
	`wasCorrected` boolean DEFAULT false,
	`originalValueIfCorrected` json,
	`appliedToEntityType` varchar(50),
	`appliedToEntityId` int,
	`appliedToAttributeKey` varchar(100),
	`appliedAttributeId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactExtractions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactImages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`imageKind` enum('site_photo','equipment_nameplate','invoice_scan','permit_scan','safety_issue','progress_photo','thermal_image','drone_capture','screenshot','drawing','diagram','other') NOT NULL,
	`takenAt` timestamp,
	`cameraMake` varchar(100),
	`cameraModel` varchar(100),
	`gpsLatitude` decimal(10,7),
	`gpsLongitude` decimal(10,7),
	`gpsAltitude` decimal(10,2),
	`locationDescription` varchar(255),
	`widthPx` int,
	`heightPx` int,
	`orientation` varchar(50),
	`containsText` boolean DEFAULT false,
	`ocrText` text,
	`ocrConfidence` decimal(5,4),
	`equipmentAssetId` int,
	`equipmentCondition` enum('good','fair','poor','damaged'),
	`constructionPhase` varchar(100),
	`milestoneReference` varchar(100),
	`thermalMinTemp` decimal(6,2),
	`thermalMaxTemp` decimal(6,2),
	`thermalAnomalyDetected` boolean,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactImages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactMeetings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`meetingType` enum('internal','external','site_visit','due_diligence','board','investor','other') NOT NULL,
	`meetingTitle` varchar(500),
	`scheduledStart` timestamp,
	`scheduledEnd` timestamp,
	`actualStart` timestamp,
	`actualEnd` timestamp,
	`durationMinutes` int,
	`location` varchar(255),
	`isVirtual` boolean DEFAULT true,
	`meetingPlatform` varchar(50),
	`meetingLink` text,
	`participants` json,
	`organizerName` varchar(255),
	`organizerEmail` varchar(255),
	`agenda` text,
	`transcriptText` text,
	`transcriptSegments` json,
	`summary` text,
	`actionItems` json,
	`decisions` json,
	`keyTopics` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactMeetings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactMessages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`messageType` enum('whatsapp','email','telegram','sms','slack') NOT NULL,
	`messageIdExternal` varchar(255),
	`threadId` varchar(255),
	`inReplyToId` varchar(255),
	`threadPosition` int,
	`fromAddress` varchar(255),
	`fromName` varchar(255),
	`toAddresses` json,
	`ccAddresses` json,
	`subject` varchar(500),
	`bodyText` text,
	`bodyHtml` text,
	`hasAttachments` boolean DEFAULT false,
	`attachmentCount` int DEFAULT 0,
	`attachmentArtifactIds` json,
	`sentAt` timestamp,
	`receivedAt` timestamp,
	`isInbound` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactMessages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifactVideo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`artifactId` int NOT NULL,
	`durationSeconds` int,
	`widthPx` int,
	`heightPx` int,
	`frameRate` decimal(6,2),
	`codec` varchar(50),
	`recordedAt` timestamp,
	`videoType` enum('site_walkthrough','inspection','meeting','drone','training','other'),
	`gpsLatitude` decimal(10,7),
	`gpsLongitude` decimal(10,7),
	`thumbnailUrl` text,
	`previewGifUrl` text,
	`hasAudio` boolean DEFAULT true,
	`transcriptText` text,
	`transcriptSegments` json,
	`keyFrames` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `artifactVideo_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `artifacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`artifactType` enum('document','image','audio','video','message','meeting','contract') NOT NULL,
	`artifactSubtype` varchar(100),
	`artifactCode` varchar(50),
	`name` varchar(500) NOT NULL,
	`description` text,
	`originalFilename` varchar(500),
	`originalFileUrl` text NOT NULL,
	`originalFileHash` varchar(64) NOT NULL,
	`originalFileSizeBytes` bigint,
	`originalMimeType` varchar(100),
	`rawMetadata` json,
	`ingestionChannel` enum('upload','email','whatsapp','api','meeting_bot','iot','manual') NOT NULL DEFAULT 'upload',
	`ingestionSourceId` varchar(255),
	`ingestionSourceMetadata` json,
	`senderType` enum('user','external_contact','system','api'),
	`senderId` int,
	`senderExternalContactId` int,
	`senderIdentifier` varchar(255),
	`receivedAt` timestamp NOT NULL DEFAULT (now()),
	`portfolioId` int,
	`projectId` int,
	`siteId` int,
	`systemId` int,
	`assetId` int,
	`lifecycleStage` enum('origination','development','due_diligence','construction','commissioning','operations'),
	`processingStatus` enum('pending','preprocessing','processed','ai_analyzing','ai_complete','failed') DEFAULT 'pending',
	`preprocessingStatus` enum('pending','cleaning','transcribing','complete','failed'),
	`preprocessingResultUrl` text,
	`aiAnalysisStatus` enum('pending','queued','analyzing','complete','failed') DEFAULT 'pending',
	`aiAnalysisStartedAt` timestamp,
	`aiAnalysisCompletedAt` timestamp,
	`aiAnalysisRunId` varchar(36),
	`aiSuggestedCategory` varchar(100),
	`aiSuggestedSubcategory` varchar(100),
	`aiCategoryConfidence` decimal(5,4),
	`confirmedCategory` varchar(100),
	`confirmedSubcategory` varchar(100),
	`categorizedBy` int,
	`categorizedAt` timestamp,
	`tags` json,
	`verificationStatus` enum('unverified','ai_verified','human_verified','rejected') DEFAULT 'unverified',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`verificationNotes` text,
	`version` int DEFAULT 1,
	`previousVersionId` int,
	`isCurrentVersion` boolean DEFAULT true,
	`supersededAt` timestamp,
	`supersededBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `artifacts_id` PRIMARY KEY(`id`),
	CONSTRAINT `artifacts_artifactCode_unique` UNIQUE(`artifactCode`)
);
--> statement-breakpoint
CREATE TABLE `assetLifecycleTracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int,
	`siteId` int,
	`assetId` int,
	`currentStage` varchar(50) NOT NULL,
	`stageEnteredAt` timestamp NOT NULL,
	`expectedStageExitAt` timestamp,
	`stageCompleteness` decimal(5,2) DEFAULT '0',
	`milestonesCompleted` int DEFAULT 0,
	`milestonesTotal` int DEFAULT 0,
	`attributesCompleted` int DEFAULT 0,
	`attributesRequired` int DEFAULT 0,
	`isBlocked` boolean DEFAULT false,
	`blockedReason` text,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` int,
	CONSTRAINT `assetLifecycleTracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contractAmendments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`amendmentArtifactId` int NOT NULL,
	`amendmentNumber` int NOT NULL,
	`amendmentDate` date NOT NULL,
	`effectiveDate` date,
	`description` text,
	`changesSummary` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contractAmendments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contractObligations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`artifactId` int NOT NULL,
	`obligationType` enum('payment','reporting','insurance','maintenance','compliance','notification','other') NOT NULL,
	`obligor` varchar(255) NOT NULL,
	`obligorRole` varchar(100),
	`description` text NOT NULL,
	`frequency` enum('one_time','monthly','quarterly','annually','ongoing'),
	`dueDate` date,
	`dueDayOfPeriod` int,
	`complianceStatus` enum('pending','compliant','non_compliant','waived') DEFAULT 'pending',
	`lastComplianceCheck` date,
	`nextDueDate` date,
	`sourceSection` varchar(50),
	`sourcePage` int,
	`sourceText` text,
	`workspaceItemId` int,
	`alertDaysBefore` int DEFAULT 30,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contractObligations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lifecycleStages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stageKey` varchar(50) NOT NULL,
	`stageName` varchar(100) NOT NULL,
	`stageOrder` int NOT NULL,
	`description` text,
	`typicalDurationMonths` int,
	`milestones` json,
	`requiredAttributes` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `lifecycleStages_id` PRIMARY KEY(`id`),
	CONSTRAINT `lifecycleStages_stageKey_unique` UNIQUE(`stageKey`)
);
--> statement-breakpoint
CREATE TABLE `stageAttributeDefinitions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lifecycleStage` varchar(50) NOT NULL,
	`attributeKey` varchar(100) NOT NULL,
	`attributeCategory` enum('identity','technical','commercial','financial','compliance','operational') NOT NULL,
	`displayName` varchar(255) NOT NULL,
	`description` text,
	`dataType` enum('text','number','date','boolean','json','file') NOT NULL,
	`unit` varchar(50),
	`required` boolean DEFAULT false,
	`requiredForStageExit` boolean DEFAULT false,
	`validationRules` json,
	`displayOrder` int,
	`displayGroup` varchar(100),
	`typicalSources` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stageAttributeDefinitions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stageMilestoneCompletions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lifecycleTrackingId` int NOT NULL,
	`milestoneKey` varchar(100) NOT NULL,
	`completedAt` timestamp NOT NULL,
	`completedBy` int,
	`evidenceArtifactIds` json,
	`notes` text,
	`verified` boolean DEFAULT false,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stageMilestoneCompletions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stageTransitionHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lifecycleTrackingId` int NOT NULL,
	`fromStage` varchar(50),
	`toStage` varchar(50) NOT NULL,
	`transitionedAt` timestamp NOT NULL,
	`transitionedBy` int,
	`daysInPreviousStage` int,
	`completenessAtTransition` decimal(5,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stageTransitionHistory_id` PRIMARY KEY(`id`)
);
